/* Replace with your SQL commands */

CREATE TABLE IF NOT EXISTS COMMENTS (
    comment_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    post_id UUID REFERENCES Posts(post_id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES Users(user_id) ON DELETE CASCADE NOT NULL,
    comment TEXT NOT NULL,
    parent_comment_id UUID REFERENCES COMMENTS(comment_id) ON DELETE CASCADE, 
    is_sub_comment BOOLEAN NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    archive_comment BOOLEAN DEFAULT FALSE,
    archive_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS LIKECOMMENT (
    likecomment_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    comment_id UUID REFERENCES COMMENTS(comment_id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES Users(user_id) ON DELETE CASCADE NOT NULL,
    like_comment BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    archive_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
